spring.application.name=prestation_service

# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/prestationdb 
spring.datasource.username=postgres
spring.datasource.password=Rivaldo
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework=DEBUG
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB Configuration

spring.data.mongodb.uri=mongodb://localhost:27017/servicedb
#spring.data.mongodb.database=servicedb

#h2 Configuration
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:prestationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


server.port=8082