spring.application.name=reservation_service

# Configuration du serveur
server.port=8081

# Base de données H2 (pour le développement)
#spring.datasource.url=jdbc:h2:mem:reservationdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Activer la console H2 (http://localhost:8081/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Configuration JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
# Activer la découverte de services

#postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/reservationdb
spring.datasource.username=postgres
spring.datasource.password=Rivaldo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator (pour le monitoring)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# JWT Validation (si vous utilisez OAuth2)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-service:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:8080/oauth2/jwks